# SPDX-FileCopyrightText: 2025 CERN
# SPDX-License-Identifier: GPL-3.0-or-later

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "external_pull_request_event" || $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_TAG != null

stages:
  - licensing-check

reuse-lint:
  image:
    name: registry.cern.ch/docker.io/fsfe/reuse
    entrypoint: [""]
  stage: licensing-check
  script:
    - cd $CI_PROJECT_DIR
    - reuse lint
